<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class IssueSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $issues = [
            [
                'issue_number' => '5475',
                'title' => 'Mercredi 15 Octobre 2025',
                'cover_image' => 'issues/canard-5475.jpg',
                'description' => 'Un rapport truqué sur le vaccin antigrippe Sanofi • La folle semaine où Macron s\'est autodissous et Retailleau autodétruit',
                'published_at' => Carbon::create(2025, 10, 15),
                'price' => 1.80,
                'digital_price' => 1.50,
                'status' => 'published',
                'stock_quantity' => 150,
                'pdf_file' => 'issues/pdf/canard-5475.pdf',
            ],
            [
                'issue_number' => '5474',
                'title' => 'Mercredi 8 Octobre 2025',
                'cover_image' => 'issues/canard-5474.jpg',
                'description' => 'Macron seul en son Palais • Retailleau consulte Sarko et Fillon • Des élections législatives les 16 et 23 novembre ?',
                'published_at' => Carbon::create(2025, 10, 8),
                'price' => 1.80,
                'digital_price' => 1.50,
                'status' => 'published',
                'stock_quantity' => 85,
                'pdf_file' => 'issues/pdf/canard-5474.pdf',
            ],
            [
                'issue_number' => '5473',
                'title' => 'Mercredi 1 Octobre 2025',
                'cover_image' => 'issues/canard-5473.jpg',
                'description' => 'La Sécu siphonnée par des liposucions • Sarkozy en prison : le Conseil constitutionnel entre dans la danse',
                'published_at' => Carbon::create(2025, 10, 1),
                'price' => 1.80,
                'digital_price' => 1.50,
                'status' => 'published',
                'stock_quantity' => 45,
                'pdf_file' => 'issues/pdf/canard-5473.pdf',
            ],
            [
                'issue_number' => '5472',
                'title' => 'Mercredi 24 Septembre 2025',
                'cover_image' => 'issues/canard-5472.jpg',
                'description' => 'Retailleau mal renseigné par son Renseignement • Les cadeaux cachés de la vente de la maison des Macron',
                'published_at' => Carbon::create(2025, 9, 24),
                'price' => 1.80,
                'digital_price' => 1.50,
                'status' => 'published',
                'stock_quantity' => 32,
                'pdf_file' => 'issues/pdf/canard-5472.pdf',
            ],
            [
                'issue_number' => '5471',
                'title' => 'Mercredi 17 Septembre 2025',
                'cover_image' => 'issues/canard-5471.jpg',
                'description' => 'Les pépites insoupçonnées de l\'empire Bolloré • Comment Poutine a joué un tour de cochon à Macron',
                'published_at' => Carbon::create(2025, 9, 17),
                'price' => 1.80,
                'digital_price' => 1.50,
                'status' => 'published',
                'stock_quantity' => 28,
                'pdf_file' => 'issues/pdf/canard-5471.pdf',
            ],
            [
                'issue_number' => '5470',
                'title' => 'Mercredi 10 Septembre 2025',
                'cover_image' => 'issues/canard-5470.jpg',
                'description' => 'Mission impossible Lecornu : "Je passe de ministre des Armées à Premier ministre désarmé !"',
                'published_at' => Carbon::create(2025, 9, 10),
                'price' => 1.80,
                'digital_price' => 1.50,
                'status' => 'published',
                'stock_quantity' => 18,
                'pdf_file' => 'issues/pdf/canard-5470.pdf',
            ],
            [
                'issue_number' => '5469',
                'title' => 'Mercredi 3 Septembre 2025',
                'cover_image' => 'issues/canard-5469.jpg',
                'description' => 'Après le hara-kiri de Bayrou • Pour Macron, retour à la kamikaze départ !',
                'published_at' => Carbon::create(2025, 9, 3),
                'price' => 1.80,
                'digital_price' => 1.50,
                'status' => 'published',
                'stock_quantity' => 12,
                'pdf_file' => 'issues/pdf/canard-5469.pdf',
            ],
            [
                'issue_number' => '5468',
                'title' => 'Mercredi 27 Août 2025',
                'cover_image' => null,
                'description' => 'Discours à l\'ONU et côté calamiteux • Macron : "Moi aussi j\'en voudrais bien, de la reconnaissance !"',
                'published_at' => Carbon::create(2025, 8, 27),
                'price' => 1.80,
                'digital_price' => 1.50,
                'status' => 'published',
                'stock_quantity' => 8,
                'pdf_file' => 'issues/pdf/canard-5468.pdf',
            ],
            [
                'issue_number' => '5467',
                'title' => 'Mercredi 20 Août 2025',
                'cover_image' => null,
                'description' => 'À Mayotte, Orange joue les malieux • Comment Bollorélingue ses ennemis au nom de la "liberté d\'expression"',
                'published_at' => Carbon::create(2025, 8, 20),
                'price' => 1.80,
                'digital_price' => 1.50,
                'status' => 'published',
                'stock_quantity' => 5,
                'pdf_file' => null,
            ],
            [
                'issue_number' => '5466',
                'title' => 'Mercredi 13 Août 2025',
                'cover_image' => null,
                'description' => 'Le vœu pieux de Lecornu bis • "Même renversé, je n\'irai pas à 1er !"',
                'published_at' => Carbon::create(2025, 8, 13),
                'price' => 1.80,
                'digital_price' => 1.50,
                'status' => 'published',
                'stock_quantity' => 3,
                'pdf_file' => null,
            ],
            [
                'issue_number' => '5465',
                'title' => 'Mercredi 6 Août 2025',
                'cover_image' => null,
                'description' => 'Le chromosome de la bêtise • Que la joie demeure • Ambitions suprêmes filinguées en plein vol',
                'published_at' => Carbon::create(2025, 8, 6),
                'price' => 1.80,
                'digital_price' => 1.50,
                'status' => 'published',
                'stock_quantity' => 0,
                'pdf_file' => null,
            ],
            [
                'issue_number' => '5464',
                'title' => 'Mercredi 30 Juillet 2025',
                'cover_image' => null,
                'description' => 'Un mal, des mots • Une justice de haut vol • SANSDESSUSDISSOUS',
                'published_at' => Carbon::create(2025, 7, 30),
                'price' => 1.80,
                'digital_price' => 1.50,
                'status' => 'published',
                'stock_quantity' => 0,
                'pdf_file' => null,
            ],
            [
                'issue_number' => '5463',
                'title' => 'Mercredi 23 Juillet 2025',
                'cover_image' => null,
                'description' => 'Comment l\'Assemblée épluche le budget • Et soudain ! Lecornu II : "Je n\'irai pas à Fieschi"',
                'published_at' => Carbon::create(2025, 7, 23),
                'price' => 1.80,
                'digital_price' => 1.50,
                'status' => 'published',
                'stock_quantity' => 0,
                'pdf_file' => null,
            ],
            [
                'issue_number' => '5462',
                'title' => 'Mercredi 16 Juillet 2025',
                'cover_image' => null,
                'description' => 'Poutine love et la paix à Gaza • Monsieur gendre et le Petit Poucet',
                'published_at' => Carbon::create(2025, 7, 16),
                'price' => 1.80,
                'digital_price' => 1.50,
                'status' => 'published',
                'stock_quantity' => 0,
                'pdf_file' => null,
            ],
            [
                'issue_number' => '5461',
                'title' => 'Mercredi 9 Juillet 2025',
                'cover_image' => null,
                'description' => 'Parlez-vous poutinien ? Le chronosome de la bêtise • Praud\'motion de la Légion d\'honneur',
                'published_at' => Carbon::create(2025, 7, 9),
                'price' => 1.80,
                'digital_price' => 1.50,
                'status' => 'published',
                'stock_quantity' => 0,
                'pdf_file' => null,
            ],
        ];

        foreach ($issues as $issue) {
            DB::table('issues')->insert([
                'issue_number' => $issue['issue_number'],
                'title' => $issue['title'],
                'cover_image' => $issue['cover_image'],
                'description' => $issue['description'],
                'published_at' => $issue['published_at'],
                'price' => $issue['price'],
                'digital_price' => $issue['digital_price'],
                'status' => $issue['status'],
                'stock_quantity' => $issue['stock_quantity'],
                'pdf_file' => $issue['pdf_file'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }

        $this->command->info('✅ 15 numéros du Canard Enchaîné ont été créés avec succès !');
    }
}
